version: '3.9'

# get db running in a cloud service
services:
  db:
    image: postgres:15
    container_name: restaurant_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d  # automatically runs init.sql

  app:
    build: ./server
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/restaurant_db
    ports:
      - "3000:3000"
    command: "nodemon server.js"